---
################################################################################
# Title      : configuration.yml
# Author     : 
# Date       : 18/05/2018
################################################################################
# Description
#-------------------------------------------------------------------------------
# Version : 1.0
# Configuration Jboss instance
################################################################################
# Description
# - copy_archives.yml
# - set_jboss-as.yml & set_datasource-pgsql
#
# Usage : ansible-playbook -i 'CMVIL2732036', configuration.yml 
################################################################################
# Wiki
#-------------------------------------------------------------------------------
# Link : 
################################################################################


################################################################################
# configuration.yml
################################################################################

- name: Configuration on front-office 
  hosts: front
  gather_facts: no

  tasks:

  - name: Check Jboss is installed
    stat: path=/opt/jboss
    register: jboss_stat

  - block:

    - name: Include role copy_archives
      include_role: 
        name: copy_archives
      with_items: "{{components}}" 
      loop_control:
        loop_var: instance

    - name: Include role set_datasource-oracle
      include_role: 
        name: set_datasource-oracle
      vars:
        instance: "{{item.instance}}"
      with_items: "{{datasource.oracle}}"

    - name: Include role set_datasource-pgsql
      include_role: 
        name: set_datasource-pgsql
      vars:
        instance: "{{item.instance}}"
      with_items: "{{datasource.pgsql}}"

    when: jboss_stat.stat.exists